# Generated by Django 3.2.2 on 2021-11-21 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_post_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
