# Generated by Django 3.2.9 on 2021-11-21 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20211116_0922'),
        ('posting', '0004_alter_category_options'),
    ]

    operations = [
    ]
